kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-zrs-disk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "azurefile-csi-zrs"