apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-csi-zrs
provisioner: file.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - dir_mode=0640
  - file_mode=0640
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict # https://linux.die.net/man/8/mount.cifs
  - nosharesock
parameters:
  skuName: Standard_ZRS
  location: eastus
  storageAccount: zrsstorage  
  shareName: share
allowedTopologies:
- matchLabelExpressions:
  - key: topology.kubernetes.io/zone   #https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/deploy/example/e2e_usage.md#option2-bring-your-own-storage-account
    values:
    - eastus2-1
    - eastus2-2

#https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/deploy/example/storageclass-azurefile-secret.yaml